Add greetings to header
willococa/hello_world pull request #2
Opened 2023-03-20 22:33 UTC by willococa

## Added list of requirements
- html with header  greeting
- ignored test.md file
- css with  styles for header  greeting

2023-03-21 21:56 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @willococa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Fair README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 21:56 UTC, Qoosim commented on README.md
> +
- [ ] It is required to have all the headings from the template used in your README file except `FAQ` heading that is optional. You're then allowed to customize your README file with appropriate information under each heading based on your project requirements. You can write `N/A` yet under any heading that's not related to your project at this moment. But all the headings must remain except `FAQ` which is optional.
Kindly follow the [template](https://github.com/microverseinc/readme-template) again and make appropriate changes to your README fiile.
**Remembe to replace the logo with your logo if you have one, otherwise remove the Microverse logo.**

2023-03-22 17:30 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @willococa 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

 - No linter errors. ✔️
 - Fair README file. ✔️
 - Correct GitHub Flow. ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 17:42 UTC, willococa commented
## Objective fullfilled

2023-03-22 17:42 UTC, merged